query products($take: Float, $skip: Float) {
  products(take: $take, skip: $skip) {
    data {
      id
      name
      product_categories {
        category {
          name
        }
      }
    }
    meta {
      total
    }
  }
}
