version: '3'

services:
  nx-base-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEV_PLATFORM=DOCKER
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
